<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-M3ID0UC" failures="1" tests="5" name="Retry Analyzer test" time="0.047" errors="0" timestamp="27 Mar 2024 08:28:06 GMT">
  <testcase classname="IRetryAnalyzerDemo.TestngFailedExecution" name="retryAnalysisTest1" time="0.013">
    <skipped/>
  </testcase> <!-- retryAnalysisTest1 -->
  <testcase classname="IRetryAnalyzerDemo.TestngFailedExecution" name="retryAnalysisTest1" time="0.001">
    <skipped/>
  </testcase> <!-- retryAnalysisTest1 -->
  <testcase classname="IRetryAnalyzerDemo.TestngFailedExecution" name="retryAnalysisTest1" time="0.0">
    <skipped/>
  </testcase> <!-- retryAnalysisTest1 -->
  <testcase classname="IRetryAnalyzerDemo.TestngFailedExecution" name="retryAnalysisTest1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at IRetryAnalyzerDemo.TestngFailedExecution.retryAnalysisTest1(TestngFailedExecution.java:25)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- retryAnalysisTest1 -->
  <testcase classname="IRetryAnalyzerDemo.TestngFailedExecution" name="retryAnalysisTest2" time="0.001"/>
</testsuite> <!-- Retry Analyzer test -->
